version: '3'
services:
  empolee_managment:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5003:5003'
      - '5004:5004'
    restart: unless-stopped
    depends_on:
      - redis
      - mongodb
      - zookeeper
      - kafka
    environment:
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL_ATLAS=mongodb://mongodb:27017/renti_v2
    networks:
      - default

  redis:
    image: redis:latest
    ports:
      - '6380:6379'
    restart: unless-stopped
    volumes:
      - redis_data:/data # Named volume for Redis data
    networks:
      - default

  mongodb:
    image: mongo:latest
    ports:
      - '127.0.0.1:27018:27017' # because docker set default ip reset and 0.0.0.0:27017 .or not hack you database
      # - '27018:27017'
      # - "127.0.0.1:27017:27017"
    volumes:
      - mongo_data:/data/db # Named volume for MongoDB data
    environment:
      # - MONGO_INITDB_ROOT_USERNAME=admin
      # - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_REPLICA_SET_NAME=rs0
    networks:
      - default

  # zookeeper:
  #   image: zookeeper:latest
  #   ports:
  #     - '2181:2181'
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper-dr
    ports:
      - '2182:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_INIT_LIMIT: 5
    networks:
      - default

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '9093:9092' # 9093:9092 --> 9093 is output port change because 9092 is used by default by all applications
    restart: unless-stopped
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    volumes:
      - kafka_data:/var/lib/kafka/data # Named volume for Kafka data (optional)
    command: bash -c "sleep 10 && /etc/confluent/docker/run" # Add 10 seconds delay before starting Kafka
    networks:
      - default

volumes:
  mongo_data:
  redis_data:
  kafka_data:

networks:
  default:
